### ISSUE TITLE
error in build , fatal error : InsetInfo.h:No such file or directory

### ISSUE THREAD

**Issue by Vanishrain** [google/earthenterprise#950] opened 2018-08-14 08:18 UTC
This happens on build. CentOS7
i use command scons -j8 release=1 build

In file included from NATIVE-REL-x86_64/fusion/autoingest/plugins/RasterProjectAsset.h:299:0,from NATIVE-REL-x86_64/fusion/autoingest/LoadAny.cpp:25:
NATIVE-REL-x86_64/fusion/autoingest/sysman/plugins/PacketGenAssetD.h:18:23: fatal error: InsetInfo.h: No such file or directory
 #include <InsetInfo.h>

In file included from NATIVE-REL-x86_64/fusion/autoingest/plugins/CombinedRPAsset.h:167:0,
                 from NATIVE-REL-x86_64/fusion/autoingest/sysman/plugins/CombinedRPAssetD.h:11,
                 from NATIVE-REL-x86_64/fusion/autoingest/plugins/RasterProductAsset.h:184,
                 from fusion/khraster/khRasterProduct.cpp:32:
NATIVE-REL-x86_64/fusion/autoingest/sysman/plugins/MosaicAssetD.h:12:27: fatal error: sysman/AssetD.h: No such file or directory
 #include <sysman/AssetD.h>
compilation terminated.

can't find file sysman/AssetD.h and InsetInfo.h

**Comment by tst-lsavoie** [comment] 2018-08-15 19:51
I'm not able to reproduce this problem. Would you double check that you installed all the prerequisites listed here: https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md?

**Comment by tst-lsavoie** [comment] 2018-11-07 17:11
There hasn't been much movement on this ticket in the last little while. I'm going to close it - feel free to reopen it if you still have a problem.

**Closed by tst-lsavoie** 2018-11-07 17:11 UTC
