### ISSUE TITLE
Error with release zip file, it reports that it requires git-lfs

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#372] opened 2017-07-21 19:34 UTC
when I downloaded the [Beta release](https://github.com/google/earthenterprise/releases/tag/5.2.0-1.beta) and extracted and build, I get this : However this is not a clone repo, so we wont be able to go ahead and ask user to  build it from release tar.gz.

Documents/earthenterprise-5.2.0-1.beta/earth_enterprise$ scons -j8 release=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 release=1 third_party
scons: Reading SConscript files ...

scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/home/asmita/Documents/earthenterprise-5.2.0-1.beta/earth_enterprise/src/SConstruct", line 471, in <module>
It appears that git lfs is not installed.  Please
install git lfs (instructions are available at
https://git-lfs.github.com).  Then run
'git lfs pull' to pull down large files before
building.
scons: *** [build] Error 1
scons: building terminated because of errors.

**Comment by tst-ccamp** [comment] 2017-07-21 19:46
The issue is that the release archive files do not contain full files for several file types, such as .gz, .tif, etc. There isn't an apparent way to fix the issue. A support ticket with GitHub has been filed. Installing git-lfs will not fix the problem.

**Comment by tst-ccamp** [comment] 2017-07-26 20:26
Rewrote this as #379 so I'll close this one.

**Closed by tst-ccamp** 2017-07-26 20:26 UTC
Labels: bug
