### ISSUE TITLE
Several fusion gtest unit tests fail on RHEL 7.3

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#15] opened 2017-03-28 00:09 UTC
Running the unit tests on RHEL 7.3 results in several failed tests. Investigate failures and correct as needed or create follow-up issues.

Test failures:
```
Running dbroot_generator_tests ...         FAILED
----------
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from Test_dbrootgen
[ RUN      ] Test_dbrootgen.Vector1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.Vector1 (4 ms)
[ RUN      ] Test_dbrootgen.ImageryTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/imagery1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/imagery1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/imagery1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.ImageryTest1 (0 ms)
[ RUN      ] Test_dbrootgen.TerrainTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/terrain1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/terrain1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/terrain1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.TerrainTest1 (1 ms)
[ RUN      ] Test_dbrootgen.ProtoFormatTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.ProtoFormatTest1 (0 ms)
[ RUN      ] Test_dbrootgen.EncodedFormatTest1
Fusion Warning:	XML file does not exist: fusion/testdata/dbroot/vector1/config.xml
Fusion Warning:	Unable to read fusion/testdata/dbroot/vector1/config.xml
unknown file: Failure
C++ exception with description "Unable to load config file fusion/testdata/dbroot/vector1/config.xml" thrown in the test body.
[  FAILED  ] Test_dbrootgen.EncodedFormatTest1 (0 ms)
[----------] 5 tests from Test_dbrootgen (5 ms total)

[----------] 1 test from Test_dbroot_combiner
[ RUN      ] Test_dbroot_combiner.CombinerTest1
Fusion Warning:	Unable to opendir(fusion/testdata/dbroot/combined1): No such file or directory
Fusion Warning:	Unable to get file info for fusion/testdata/dbroot/combined1/combined: No such file or directory
fusion/dbroot/dbroot_generator_tests.cc:234: Failure
Value of: khFilesEqual(output_file, golden_file)
  Actual: false
Expected: true
[  FAILED  ] Test_dbroot_combiner.CombinerTest1 (3 ms)
[----------] 1 test from Test_dbroot_combiner (3 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (8 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] Test_dbrootgen.Vector1
[  FAILED  ] Test_dbrootgen.ImageryTest1
[  FAILED  ] Test_dbrootgen.TerrainTest1
[  FAILED  ] Test_dbrootgen.ProtoFormatTest1
[  FAILED  ] Test_dbrootgen.EncodedFormatTest1
[  FAILED  ] Test_dbroot_combiner.CombinerTest1

 6 FAILED TESTS
...
Running geImageWriter_unittest ...         FAILED
----------
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from geImageWriterTest
[ RUN      ] geImageWriterTest.ImageWriterBasicTest
ERROR 4: fusion/testdata/testmask.tif: No such file or directory
----------
...
Running idl_tests ...                      FAILED
----------
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
common/khxml/idl_tests.cc:39: Failure
Value of: khDirExists(source_dir_)
  Actual: false
Expected: true
[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 10 tests.
[  FAILED  ] 0 tests, listed below:

 0 FAILED TESTS
----------
Running polygontoqtnodes_unittest ... (Seems to hang)
...
Running polymask_unittest ...              FAILED
----------
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from PolyMaskTest
[ RUN      ] PolyMaskTest.GoldStandardTest
[       OK ] PolyMaskTest.GoldStandardTest (1 ms)
[ RUN      ] PolyMaskTest.GeodataPreservationTest
ERROR 4: fusion/testdata/i3SF15-meter.tif: No such file or directory
ERROR 4: fusion/testdata/i3SF15-meter.tif: No such file or directory
Fusion Fatal:	Unable to open fusion/testdata/i3SF15-meter.tif. Exception: fusion/testdata/i3SF15-meter.tif: Unable to open. Even GDALOpen failed!
----------

```

**Comment by andreisel** [comment] 2017-04-18 01:19
Yes, the issue is that in tests we have a path relative to src.
I believe it should work if you run from src directory:
./bin/tests/dbroot_generator_tests
./bin/tests/RunAllTests.pl

**Comment by tst-ppenev** [comment] 2017-04-20 19:17
@tst-ccamp: I didn't seem to get the error when running from <src>.  Can you clarify how this is expected to be run.  (Expected vs. observed behavior.) I am a little unclear about what is being fixed.

Is `RunAllTests.pl` supposed to be run after an installation, or during a build?  Is it run from `scons`?  (I only see the copy command.)

**Comment by tst-ccamp** [comment] 2017-04-20 19:41
@tst-ppenev This is how you run the unit tests. You can run them from the src directory or from within NATIVE-XXX-x86_64/bin/tests. It isn't obvious that you are supposed to run it from the src directory and as @bradh pointed out on the pull request if you run the tests from the src directory it will create temporary files in your git repo which isn't a good practice. It's much better if all of it was run within the tests directory.

**Comment by tst-ppenev** [comment] 2017-04-20 19:57
@tst-ccamp: Is a developer supposed to run this after building? Or after installing? Should there be a `scons` target for running these tests?

**Comment by bradh** [comment] 2017-04-20 20:29
I see unit tests as an after-build and before-install step.

Ideally the tests would be run on every build, but (for me) they can be a bit slow, so a separate scons target would make sense.

**Comment by tst-ppenev** [comment] 2017-04-20 21:22
Yeah.  You can also pass parameters to `scons` builds, like `optimize`.  We could add one for running unit tests.

**Comment by irteza123** [comment] 2017-04-26 03:07
Guys. i am facing same issue on Ubuntu 14.04. what can i do ??

**Comment by bradh** [comment] 2017-04-26 06:30
@irteza123 As I pointed out on your other ticket, it is being worked. You can test the pull request if you're comfortable with git (see https://github.com/google/earthenterprise/pull/77 for the branch), or you can wait for it to be merged.

Other than that, all help is appreciated.

**Closed** 2017-04-26 18:24 UTC
Labels: bug
