### ISSUE TITLE
download_tutorial.sh has no execute permissions

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#394] opened 2017-07-30 11:39 UTC
I had to change the permissions to make it run:

$ /earthenterprise/earth_enterprise/src/installer$ sudo  /opt/google/share/tutorials/fusion/download_tutorial.sh 
sudo: /opt/google/share/tutorials/fusion/download_tutorial.sh: command not found

$:~/earthenterprise/earth_enterprise/src/installer$ sudo chmod 777  /opt/google/share/tutorials/fusion/download_tutorial.sh 

$:~/earthenterprise/earth_enterprise/src/installer$ sudo /opt/google/share/tutorials/fusion/download_tutorial.sh
--2017-07-30 04:35:37--  http://data.opengee.org/FusionTutorial-Full.tar.gz
Resolving data.opengee.org (data.opengee.org)... 216.58.192.16, 2607:f8b0:4005:801::2010
Connecting to data.opengee.org (data.opengee.org)|216.58.192.16|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 653418120 (623M) [application/gzip]
Saving to: ‘/tmp/FusionTutorial-Full.tar.gz’

**Comment by tst-ccamp** [comment] 2017-07-31 14:36
This is a duplicate of #362

**Closed by tst-ccamp** 2017-07-31 14:36 UTC
Labels: duplicate
