### ISSUE TITLE
download_tutorial.sh script should check if it's running as root

### ISSUE THREAD

**Issue by tst-lsavoie** [google/earthenterprise#438] opened 2017-08-14 18:09 UTC
The download_tutorial script downloads the tutorial files to the correct location for users.  This script must be run as root to have permission to write the tutorial files to the correct location.  If the script is not run as root it will download the files (which takes several minutes) and then fail.  To save users time, this script should ensure that it is running as root before attempting to download the files.

**Comment by tst-ccamp** [comment] 2017-08-14 19:05
Duplicate of #377

**Closed by tst-ccamp** 2017-08-14 19:05 UTC
Labels: duplicate
