### ISSUE TITLE
Portable server windows build fails

### ISSUE THREAD

**Issue by tst-jhaight** [google/earthenterprise#976] opened 2018-09-06 16:55 UTC
Using the mingw g++ 8.1.0 (latest available [here](https://sourceforge.net/projects/mingw-w64/files/latest/download)) attempting to compile portable server fails for both 32 and 64bit with the following error message:
`cmath:1121:11: error: '::hypot' has not been declared`

It appears the root cause of this issue is [a cpython bug](https://bugs.python.org/issue11566) which has not been fixed yet.  To work around this issue `-D_hypot=hypot` must be added to the Windows g++ command to compile `glc_unpacker_wrap.cxx`.

Additionally `-DMS_WIN64` needs to be added to g++ commands in order to link successfully when using mingw64.

**Comment by tst-ppenev** [comment] 2018-09-10 14:32
@tst-jhaight, please specify what installation of Python you're using.  This bug is logged for Python 3.3.  Portable Server runs with Python 2.7.

**Comment by tst-jhaight** [comment] 2018-09-10 15:54
@tst-ppenev 
Sorry I forgot to specify but I'm using python 2.7.15 and seeing the same behavior described by that bug.

`MS_WIN64` fixes a problem that seems to be caused by a few factors.  The swig generated implementation of `glc_unpacker_wrap.cxx` is using `Py_InitModule`.  Python's `modsupport.h` is supposed to rename `Py_InitModule` for 64bit systems.  `MS_WIN64` is used to help determine 64 vs 32 on windows but for some reason it isn't set with mingw64.

**Comment by tst-ppenev** [comment] 2018-09-10 16:49
@tst-jhaight, thanks.

So, you think the problem is `swig` only supports 32-bit Python extensions?  I wonder why I didn't see this problem on 64-bit systems before?

**Comment by tst-jhaight** [comment] 2018-09-10 17:18
@tst-ppenev I really still haven't figured out exactly what is the absolute root cause.  I don't think it is swig at fault unless they should include or define something in the auto-generated code.  It at least looks to me like including python.h should be all that is needed and they do that.

It could be caused by where we are pulling include files from.  I see a lot of the .h files for python are in both mingw's `opt/include/python2.7` and the python installation's `include` directory but they are not the same file content.  Maybe each one could expect some behavior from the other which isn't met?  It at least seems limited to only showing up for 64bit windows builds.

**Comment by tst-ppenev** [comment] 2018-09-10 18:40
Oh, you have a MinGW Python installation?

You could try specifying an include directory explicitly when compiling to override the default path.  I think we'd want to make sure GCC is using the header files corresponding to the Python interpreter that's running the build script.

**Comment by tst-jhaight** [comment] 2018-09-10 18:55
I didn't intentionally select to include python with mingw but it does appear to have a lot of what we'd need for using python (also happens to include 2.7).  I also have a standard python.org 2.7.15 installation not related to mingw.  The build script is running the stand alone python interpreter and attempting to include files associated with the interpreter.

I tried switching our `g++` compile commands to point it to the mingw files for inclusion and linking.  It does compile and link without defining any special macros.  Attempting to run doesn't go well though and it complains about a missing (nameless) .dll.  From [this link](https://bugs.python.org/issue4709), it seems like python and mingw isn't a super well supported combination and other people have been hitting this issue for a few years.

**Comment by tst-blaird** [comment] 2018-09-10 21:00
PR approved and merged.

**Closed by tst-blaird** 2018-09-10 21:00 UTC
