### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by reinjunon** [google/earthenterprise#234] opened 2017-06-10 13:10 UTC
This happens on build. CentOS7 minimal ISO i.e

 scons -j8 release=1 build

In file included from NATIVE-DBG-x86_64/fusion/autoingest/plugins/CombinedRPAsset.h:167:0,
                 from NATIVE-DBG-x86_64/fusion/autoingest/sysman/plugins/CombinedRPAssetD.h:11,
                 from NATIVE-DBG-x86_64/fusion/autoingest/plugins/RasterProductAsset.h:184,
                 from fusion/khraster/khRasterProduct.cpp:32:
NATIVE-DBG-x86_64/fusion/autoingest/sysman/plugins/MosaicAssetD.h:12:27: fatal error: sysman/AssetD.h: No such file or directory
 #include <sysman/AssetD.h>
                           ^
compilation terminated.

**Comment by asmitaw** [comment] 2017-06-12 02:56
can you please run 
scons release=1 build

and see what you get. 

Additionally what g++ compiler version you have ?
did you run all CentOS specific installs from : https://github.com/google/earthenterprise/wiki/Build-Instructions

**Comment by tst-ccamp** [comment] 2017-06-12 15:14
This is strange. It appears to not be picking up the "release=1" option. It's building to the NATIVE-DBG-x86_64 directory instead of the NATIVE-REL-x86_64 directory. @reinjunon which directory are you building from and have you updated the repo to the latest version of the master branch?

**Comment by tst-ahernandez** [comment] 2017-06-13 14:52
Hi @reinjunon! Are you still seeing this error? If so, please post an update here or join our slack channel for discussion: http://slack.opengee.org

**Comment by asmitaw** [comment] 2017-06-13 23:47
there might have been a typo about release vs internal? 
 I just cloned fresh and built scons -j8 release=1 build and it builds fine.

**Comment by asmitaw** [comment] 2017-06-13 23:52
And yes, I confirmed that it builds NATIVE-REL-x86_64 for release=1, which is what is expected

**Comment by reinjunon** [comment] 2017-06-13 23:54
I'll have another shot at it later.



Regards,
Junon lim


-------- Original message --------

**Comment by micklang** [comment] 2017-06-14 09:33
I'm having huge issues building on CentOS7-- first the python test to see if git-lfs was installed was flawed (I swear to you, I'm following the build instructions perfectly). Once I tweaked the python script to change len = 500 to 50, it worked just fine-- up until I run the scons -j8 release=1 build.

I'm getting the following:
scons: Reading SConscript files...
sonds: *** Source `['landing_page/manual'] of Install() contains one or more non-files. Install() source must be one or more files.
File "src/scons/khEnvironment.py", line 359, in install

What gives? Unfortunately, I can't build this server connected to the internet, so I'm having to burn cd's with the correct rpm's and sneaker net'ing them.

Is anyone else with CentOS7 having these issues?

**Comment by bradh** [comment] 2017-06-14 10:35
@micklang I doubt Centos is getting as much testing as Ubuntu (I'm certainly not testing on that) - you might like to run your trials on a networked machine first. Note that you are installing software that is still in development, so don't expect this to work like a production release.

The error looks like you possibly didn't get a full checkout (although I've never seen it, and its hard to tell since you aren't describing what debugging you've tried). For example, what is in the docs/landing_page/manual directory? Does it match https://github.com/google/earthenterprise/tree/master/earth_enterprise/docs/landing_page/manual ?

**Comment by reinjunon** [comment] 2017-06-14 10:42
Somehow it worked this time on rebuild.


Thanks all.


Regards,
Junon


________________________________

**Comment by tst-ccamp** [comment] 2017-06-14 15:23
@micklang It looks like the git-lfs check was working correctly. It's checking to see if the *.gz files have been downloaded. This is the job of git-lfs. We have to use git-lfs currently in order to maintain a reasonably sized repo to conform to GitHub standards. If you have a gzip file that is less than 500 bytes, I guarantee that git-lfs has not done its job. The change you made will make the check pass, but it doesn't mean that you have valid gzip files. You'll need to make sure that git-lfs has done it's download of the files in the repo before moving the repo to the disconnected build machine. Please see [git-lfs documentation](https://git-lfs.github.com/) for more info.

As for the scons error, this indicates that it can't find the directory "[earth_enterprise/docs/landing_page/manual](https://github.com/google/earthenterprise/tree/master/earth_enterprise/docs/landing_page/manual)". I've verified that it's present in the repo, so that probably means that you didn't get a full/clean checkout of the repo. I've seen this happen due to git-lfs not being installed properly when doing the clone. So, this is most likely related to your other issue with the git-lfs check. 

My recommendation is to (on a machine connected to the internet) install git-lfs, start the clone over, follow method 2 under step 5 of the [build instructions](https://github.com/google/earthenterprise/wiki/Build-Instructions). You can manually verify that both the "earth_enterprise/docs/landing_page/manual" directory exists as well as the tar.gz files under earth_enterprise/third_party are valid. You can use the apache archive "[httpd-2.2.32.tar.gz](https://github.com/google/earthenterprise/blob/master/earth_enterprise/third_party/apache2/httpd-2.2.32.tar.gz)" as an example. If git-lfs is successful, it will be approximately 7.33 MB. Then you can transfer the files to your disconnected machine. We don't normally test using this configuration, but once you have all the prerequisite libraries installed, you should be able to run the build build. The scons build and install targets themselves do not require internet connection in order to work.

Good luck! If you have any more problems, please open a new issue.

**Comment by tst-ccamp** [comment] 2017-06-14 15:25
@reinjunon Thanks for letting us know that you were successful in the build. I'll go ahead and close this issue. Please, let us know if you run into any other problems.

**Closed by tst-ccamp** 2017-06-14 15:25 UTC
Labels: question
