### ISSUE TITLE
copyright is old in info.txt for portable

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#398] opened 2017-07-30 15:30 UTC
http://localhost:9335/earth/info.txt - Not sure if its okay to update ( some scripts designed to read a particular line number / keyword and parse these  text files, so we need to verify and then update)

**Comment by tst-ccamp** [comment] 2017-07-31 14:36
Duplicate of #397

**Closed by tst-ccamp** 2017-07-31 14:36 UTC
Labels: duplicate
