### ISSUE TITLE
Uninstall scripts are not copied to opt/google

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#334] opened 2017-07-13 11:06 UTC
To be consistent with the 5.1.3, we should maintain the uninstall scripts even after temp staged directory is removed.

hence deploy following scripts in the location similar to 5.1.3 i.e.  somewhere on /opt/google

earthenterprise/earth_enterprise/src/installer/uninstall_fusion.sh and
earthenterprise/earth_enterprise/src/installer/uninstall_geserver.sh

**Comment by tst-lsavoie** [comment] 2017-07-13 16:35
Duplicate of #303.  That one is already in the 5.2.1 milestone, so I'm going to close this one.

**Closed by tst-lsavoie** 2017-07-13 16:35 UTC
Labels: duplicate
