### ISSUE TITLE
Unit tests failing and looping

### ISSUE THREAD

**Issue by Geaven** [google/earthenterprise#1513] opened 2019-10-28 03:52 UTC
I have run the build on my Red Hat Enterprise 7.7 after installing all the prerequisites without any hiccups but when running the unit tests, these 2 errors keep getting thrown at me:

" at
  common/tests/geFileUtils_test.cpp:129
ERROR: expected "memcmp(expected_buff, buff, kBuffSize)" == "0
       actual  "memcmp(expected_buff, buff, kBuffSize)" = 136 , "0" = 0
" at
  common/tests/geFileUtils_test.cpp:130
ERROR: expected "num_read" == "kBuffSize
       actual  "num_read" = 0 , "kBuffSize" = 4096
and then it just loops over those errors over and over again as shown below:
![gee tests](https://user-images.githubusercontent.com/30004743/67650810-6c02e980-f979-11e9-900b-1e8d7b096662.jpg)

Does anyone have any idea what it might be?

**Comment by tst-lsavoie** [comment] 2019-10-30 14:13
I have to admit I've never seen that error before. Let me spin up a RHEL 7.7 VM and see what I can figure out.

**Comment by tst-lsavoie** [comment] 2019-10-30 17:34
I was not able to reproduce this issue. The unit tests passed for me on RHEL 7.7. Did you notice any errors during the build phase that might explain the problem?

**Comment by Geaven** [comment] 2019-10-31 03:30
I think it could be because it's on an Azure VM and it's installed on an attached data disk that might not have been mounted with the right specifications.

**Comment by tst-rwildes** [comment] 2019-11-11 04:15
I've seen this error but haven't had time to dig into why it happens.  I've seen it on docker containers in a variety of OS versions.

**Comment by tst-lsavoie** [comment] 2020-01-22 00:08
Closing this issue because there hasn't been any activity in several months. If you have more trouble, feel free to reopen this issue or create a new one.

**Closed by tst-lsavoie** 2020-01-22 00:08 UTC
