### ISSUE TITLE
gepolymaskgen segfaults with specific inputs

### ISSUE THREAD

**Issue by sibucan** [google/earthenterprise#515] opened 2017-09-21 18:46 UTC
I get a segmentation fault when running gepolymaskgen. 

I'm trying to create a custom mask like the one shown in [this](http://www.opengee.org/geedocs/answer/4525555.html#h.frsdlq-dl14oj) tutorial. The coastline mask that I use is a full-resolution world coastline shapefile named GSHHS_f_L1.shp located on the Data/ folder. The 44-tile mosaic of .jp2 files is located on the Imagery/ folder. The compressed input files (mosaic .khvr and world coastlines file) are located in [this](https://drive.google.com/open?id=0B1_3KrIKN1M1aHM5OWtzRmd5ZWc) Google Drive link. I'm running the command on a machine with 24 cores and 64 GB of RAM, since when I tried this earlier on a machine with 8 GB I was getting out of memory bad_alloc errors. However, after moving to the more powerful machine, this is my output:

```
user@gee:/gevol/src/Imagery/San_Diego_2014_NAIP_JP2$ time /opt/google/bin/gepolymaskgen --base_image san_diego_2014_mosaic_naip_jpg2000.khvr --invert --feather -300 --feather_border 1 --and_neg_mask /gevol/src/Data/gshhg-shp-2.3.6/GSHHS_shp/f/GSHHS_f_L1.shp  --invert --output_mask san_diego_2014_naip-custom-mask.tif
Fusion Notice:  Base image: san_diego_2014_mosaic_naip_jpg2000.khvr
Fusion Notice:  san_diego_2014_mosaic_naip_jpg2000.khvr width: 55666 height: 57853
Fusion Notice:  north: 3.878727e+06 south: 3.820874e+06 east: -1.300350e+07 west: -1.305917e+07
Fusion Notice:  File type: KHM/Keyhole Mosaic
Fusion Notice:  Projection : 'PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Mercator_Auxiliary_Sphere"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["Standard_Parallel_1",0.0],PARAMETER["Auxiliary_Sphere_Type",0.0],UNIT["Meter",1.0],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"]]'
Fusion Notice:  Invert
Fusion Notice:  Feather -300
Fusion Notice:  Feather border 1
Fusion Notice:  AND mask: /gevol/src/Data/gshhg-shp-2.3.6/GSHHS_shp/f/GSHHS_f_L1.shp
Fusion Notice:  Invert
Fusion Notice:  Output mask: san_diego_2014_naip-custom-mask.tif
Fusion Notice:  Setting base image san_diego_2014_mosaic_naip_jpg2000.khvr.
Fusion Notice:  Inverting current mask.
Fusion Notice:  Setting feather -300.
Fusion Notice:  Feather border is on.
Fusion Notice:  Writing alpha file san_diego_2014_naip-custom-mask.tif
Fusion Notice:  Executing: gdal_rasterize -b 1 -burn 255 -l GSHHS_f_L1 /gevol/src/Data/gshhg-shp-2.3.6/GSHHS_shp/f/GSHHS_f_L1.shp san_diego_2014_naip-custom-mask.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Total tiles to process: 1
Segmentation fault (core dumped)

real    10m5.050s
user    6m58.480s
sys     0m26.832s
```

**Comment by tst-lsavoie** [comment] 2017-09-27 21:05
Just FYI, I was able to reproduce this on a machine with 16 GB of RAM.  It looks like the memory usage tops out around 12.5 GB.

**Comment by tst-lsavoie** [comment] 2017-09-28 21:20
Valgrind reports the following.  This points us to where the corrupted memory is used, not where the memory is becoming corrupted, but it's a start.
```
==28055== Invalid read of size 4
==28055==    at 0x4141B8: ComputeSAT(int*, unsigned char, int) (boxfilter.cpp:114)
==28055==    by 0x41421E: ComputeSATSpanValue(int**, int, unsigned char, int) (boxfilter.cpp:124)
==28055==    by 0x4139BA: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:295)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055==  Address 0x287f9e03c is 4 bytes before a block of size 135,716,004 alloc'd
==28055==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28055==    by 0x41333F: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:187)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055== 
==28055== Invalid read of size 4
==28055==    at 0x4141AC: ComputeSAT(int*, unsigned char, int) (boxfilter.cpp:113)
==28055==    by 0x41421E: ComputeSATSpanValue(int**, int, unsigned char, int) (boxfilter.cpp:124)
==28055==    by 0x4139BA: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:295)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055==  Address 0x287f9e03c is 4 bytes before a block of size 135,716,004 alloc'd
==28055==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28055==    by 0x41333F: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:187)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055== 
==28055== Invalid read of size 4
==28055==    at 0x4141B8: ComputeSAT(int*, unsigned char, int) (boxfilter.cpp:114)
==28055==    by 0x41421E: ComputeSATSpanValue(int**, int, unsigned char, int) (boxfilter.cpp:124)
==28055==    by 0x413B89: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:329)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055==  Address 0x287f9e03c is 4 bytes before a block of size 135,716,004 alloc'd
==28055==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28055==    by 0x41333F: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:187)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055== 
==28055== Invalid read of size 4
==28055==    at 0x4141AC: ComputeSAT(int*, unsigned char, int) (boxfilter.cpp:113)
==28055==    by 0x41421E: ComputeSATSpanValue(int**, int, unsigned char, int) (boxfilter.cpp:124)
==28055==    by 0x413B89: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:329)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055==  Address 0x287f9e03c is 4 bytes before a block of size 135,716,004 alloc'd
==28055==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28055==    by 0x41333F: BoxFilterTiledImage::BoxFilter(int, int, unsigned char) (boxfilter.cpp:187)
==28055==    by 0x41241F: InMemoryFeatherer::InMemoryFeatherer(unsigned char*, int, int, int, unsigned char) (Featherer.cpp:67)
==28055==    by 0x40F19F: fusion_tools::PolyMask::FeatherMaskData(std::vector<unsigned char, std::allocator<unsigned char> >*, int, unsigned char) (polymask.cpp:645)
==28055==    by 0x40EF63: fusion_tools::PolyMask::FeatherMask(int, unsigned char) (polymask.cpp:597)
==28055==    by 0x40DA64: fusion_tools::PolyMask::BlendMasks(fusion_tools::PolyMask::BuildMaskCommand, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::vector<unsigned char, std::allocator<unsigned char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*) (polymask.cpp:295)
==28055==    by 0x40D60D: fusion_tools::PolyMask::BuildMask() (polymask.cpp:238)
==28055==    by 0x40BB33: main (gepolymaskgen.cpp:490)
==28055== 
```

**Comment by tst-lsavoie** [comment] 2017-10-11 20:15
@sibucan I have a potential fix for this here: https://github.com/tst-lsavoie/earthenterprise/tree/gepolymaskgen-segfault-515.  Would you download that version and see if it fixes the segfault and also make sure the mask looks reasonable?

**Closed** 2017-10-17 21:47 UTC
Labels: bug
