### ISSUE TITLE
Not able to publish the pushed database from server

### ISSUE THREAD

**Issue by gautamp86** [google/earthenterprise#199] opened 2017-05-31 04:40 UTC
After trying to publish the pushed database from server it gives an error (StatusCode:-1)
PFA for more information
![publish_error](https://cloud.githubusercontent.com/assets/28753606/26615998/ff112ab2-45e8-11e7-96e7-818d2127630b.PNG)
![gee_check](https://cloud.githubusercontent.com/assets/28753606/26615999/ff17144a-45e8-11e7-8888-cfbd71bb5e7a.PNG)
Kindly guide me to resolve this issue

**Comment by asmitaw** [comment] 2017-05-31 04:58
I believe that is because of the gevol is running out of space.
The part of the message points to the transfer (i.e. copy ) failing and 
the 1st error in the geecheck points to the same thing.

**Comment by gautamp86** [comment] 2017-05-31 06:45
Thanks for the reply. I have checked that also. But the disk/gevol has enough space. PFA for more details.
Is gee server allocate default size? If yes, then how to increase the limit?
![gevol_space](https://cloud.githubusercontent.com/assets/28753606/26619149/d3e386b6-45fa-11e7-9763-2164457459fd.PNG)

**Comment by bradh** [comment] 2017-05-31 07:05
Is that everything? Do you have a small `/tmp` partition?

**Comment by gautamp86** [comment] 2017-05-31 07:11
Yes. Everything is under root.

**Comment by asmitaw** [comment] 2017-06-01 00:15
https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/server/wsgi/serve/serve_utils.py#L416  - this code gets called when transfer happens. This is copy/ transfer  with some overrides like force_copy

you can try copying the manifest manually/commandline to see there are enough "read" permissions.

Also look at the error logs and access log for more info : /opt/google/gehttpd/logs/ ( match the time when you saw error or reproduce the error and see the latest log info)

**Comment by asmitaw** [comment] 2017-06-05 15:54
@gautamp86  Can we resolve this as answered, can you please update if there is still an issue with the error details from the access/ error log ?

**Comment by asmitaw** [comment] 2017-06-15 04:51
this is happening for me for the release as well as internal build ( clean one ), I tried changing the permissions once to geapacheuser:gegroup and it worked , whereas second time I deployed it did not fix the issue.

I believe it could be a regression or something is left behind from the old install that is not getting cleaned by the uninstall_* scripts.

Anyways this is pretty annoying.

**Comment by tst-ccamp** [comment] 2017-06-15 16:14
Fixed in #240, so closing this issue

**Closed by tst-ccamp** 2017-06-15 16:14 UTC
Labels: bug
