### ISSUE TITLE
Error in publish of SSL-enabled database

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#731] opened 2018-03-03 06:18 UTC
![screen shot 2018-03-02 at 10 03 20 pm](https://user-images.githubusercontent.com/28072052/36931276-534b0f2e-1e67-11e8-8629-711a3681dc11.png)
Steps to reproduce:

1.  Import certs and key | 1.  Obtain ‘geetestserver.crt’, ‘geetestserver.key.pem’, and ‘ca.cert.crt’ 
1.  Copy certs and key to proper location  1. ‘sudo cp geetestserver.crt /opt/google/gehttpd/conf’.  2. ‘sudo cp geetestserver.key.pem /opt/google/gehttpd/conf’  3. ‘sudo cp ca.cert.crt /opt/google/gehttpd/conf’ 
1. Modify /etc/hosts file to add ‘geetestserver’   1. ‘sudo vi /etc/hosts’  2. Add ‘127.0.1.1 geetestserver’. 
 3. Save and exit.
1. Edit gehttpd.conf and httpd-ssl.conf to enable SSL   1. ‘sudo vi /opt/google/gehttpd/conf/gehttpd.conf’   2. Uncomment and change ‘#ServerName www.example.com’ to ‘ServerName geetestserver:80’   3. Check that ‘Include conf/extra/httpd-ssl.conf’ appears and uncomment it.  4. Save and exit  5. ‘sudo vi /opt/google/gehttpd/conf/extra/httpd-ssl.conf’  6. Uncomment and change ‘#ServerName www.example.com’ to ‘ServerName geetestserver:443’  7. Change line ‘SSLCertificateFile /opt/google/gehttpd/conf/server.crt’ to ‘SSLCertificateFile /opt/google/gehttpd/conf/geetestserver.crt’  8. Change line ‘SSLCertificateKeyFile /opt/google/gehttpd/conf/server.key’ to ‘SSLCertificateKeyFile /opt/google/gehttpd/conf/geetestserver.key.pem’  9. Uncomment and change line ‘#SSLCertificateChainFile /opt/google/gehttpd/conf/server-ca.crt’ to ‘SSLCertificateChainFile /opt/google/gehttpd/conf/ca.cert.crt’’  10. Save and exit  11. Restart geserver: ‘sudo /etc/init.d/geserver restart’
1. Enable SSL Virtual Hosts   1. ‘sudo /opt/google/bin/geserveradmin --addvh test_ssl --ssl’  2. Restart geserver: ‘sudo /etc/init.d/geserver restart’
1. Set firewall rules for https support   1. sudo firewall-cmd --add-port=443/tcp --permanent  2. sudo firewall-cmd --reload
1. Add CA cert to browser   1. Go to Settings->Preferences  2. Click on ‘Advanced -> View Certificates” 
 3. Click on “Import”.  4. Navigate to, and select, “ca.cert.crt”  5.  On the ‘Certificate Authority’ pop-up, just enable ‘Trust this CA to identify websites’; leave the other two alone.  6. Click “Ok”.
& Go to ssl-enabled admin page | 1. Open ‘https://geetestserver:443/admin’.  2. Click ‘Advanced’.  3. Click ‘proceed to geetestserver (unsafe)’.
1.  Login with ‘geapacheuser’ / ’geeadmin’. | 4. The badge in front on the URL should show ‘Secure’.
* Publish database using ‘test_ssl’ virtual host | 1. Select a 2D map database.2. Click ‘publish’.3. Select ‘test_ssl’ from the dropdown for Virtual Host.  4. Click ‘publish’.
1. ERROR

**Comment by tst-ccamp** [comment] 2018-03-08 17:25
I noticed this yesterday also. We need to see if this also effects command-line operation. It may be that the server/CA cert needs to be configured for the system as well

**Comment by tst-ccamp** [comment] 2018-03-08 17:27
By the way, this error also occurs for all the other virtual hosts, not just the secure one. You'll get the same error by selecting "public". The problem comes from connecting to the admin console via HTTPS. If you connect via HTTP instead, then you don't see this issue for any of the virtual hosts.

**Comment by tst-jhaight** [comment] 2018-04-19 12:41
At least a portion of this issue appears to be caused by [this change to python certificate implementation](https://access.redhat.com/articles/2039753).  This appears to affect RHEL7 and CentOS7.

To work around the issue you can either disable python certificate verification (instructions in the above link) or [import](http://gagravarr.org/writing/openssl-certs/others.shtml#ca-openssl) the trusted certificate to /var/opt/google/openssl/certs.

**Comment by tst-jhaight** [comment] 2018-05-18 17:27
This issue was addressed in 5.2.2 and the temporary fix was determined to be the best solution once the server was changed to connect to itself via localhost.

**Closed by tst-jhaight** 2018-05-18 17:27 UTC
Labels: bug
