### ISSUE TITLE
Slack link does not work from the project landing page.

### ISSUE THREAD

**Issue by tst-awankhede** [google/earthenterprise#529] opened 2017-10-02 19:06 UTC
http://slack.opengee.org/ this is the link at present.

Need to update to http://opengee.slack.com

**Comment by tst-lsavoie** [comment] 2017-10-11 20:09
This is now fixed.  http://slack.opengee.org is working again.

**Closed by tst-lsavoie** 2017-10-11 20:09 UTC
Labels: bug

**Comment by phoemke** [comment] 2017-12-23 00:43
This issue appears to have resurfaced (rechecked over the last few days), with the browser being unable to connect to 104.196.254.216:3000

Is anyone able to confirm and/or troubleshoot? Thanks!

**Comment by tst-ccamp** [comment] 2017-12-27 01:43
@phoemke It looks like the problem is resolved now. I'm able to connect to http://slack.opengee.org/ Can you give it another try?
