### ISSUE TITLE
Issues when building with scons

### ISSUE THREAD

**Issue by sibucan** [google/earthenterprise#319] opened 2017-07-11 13:34 UTC
On a fresh system running Ubuntu 14.04 and gcc/g++ 4.4, I try running `scons -j4 release=1 build` after doing all the previous steps (including installing all the dependencies by running apt-get install in step 4), and I come across this error:

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j4 release=1 third_party
scons: Reading SConscript files ...

scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/home/user/earthenterprise/earth_enterprise/src/SConstruct", line 471, in <module>
Checking for C library gtest... no
Checking for C header file libpng12/png.h... no
libpng12 must be installed!
scons: *** [build] Error 1
scons: building terminated because of errors.
```
Which is strange because I installed gtest and libpng12, and the headers appear in /usr/include but somehow scons doesn't seem to be able to find them. I tried modifying my $PATH to include that directory but that did not work. Is there something important that I am missing?

**Comment by tst-awankhede** [comment] 2017-07-11 22:41
I remember similar issue , something in the cache is stuck and not recognizing the install of gtest or libpng*  
--config=force and see if it solves your problem.
e.g.  scons -j8 release=1 build   --config=force

**Comment by sibucan** [comment] 2017-07-12 11:27
@tst-awankhede I tried that initially and it made no difference. It displays the same errors. This is what I get when I run `apt list --installed | grep libpng` (trying to see if there are any broken dependencies)
```
WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libpng12-0/trusty-updates,trusty-security,now 1.2.50-1ubuntu2.14.04.2 amd64 [installed]
libpng12-dev/trusty-updates,trusty-security,now 1.2.50-1ubuntu2.14.04.2 amd64 [installed]
```
So they are installed, when I check for them. I tried restarting the machine, and now I'm just going to try re-cloning the entire project again. Any clues as to what is going on?

**Comment by tst-ccamp** [comment] 2017-07-12 17:20
I've never seen this happen when the libraries are actually installed and there is no caching issue. You can try disabling the scons check for the library and see if the compile task has any issues finding it. If that's the case then there must be some issue with the scons check. However, it could be that the system default include path is not set correctly or not being picked up by scons. It may also be that the library has subtly changed in a recent update.

**Comment by sibucan** [comment] 2017-07-12 21:00
@tst-ccamp I went into '~/earthenterprise/earth_enterprise/src/common/SConscript' and commented out the header check for libpng12. The compilation went much farther ahead this time, but stopped at this error:
```
gcc -o NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/src/glu/sgi/libtess/priorityq.o -c -O2 -DNDEBUG -pipe -pthread -Wall -Wno-parentheses -Wno-error=unused-result -Wno-error=unused-local-typedefs -Wno-error=unused-but-set-variable -D_LARGEFILE64_SOURCE -DQT_THREAD_SUPPORT -DQT_NO_ASCII_CAST -DQT_CLEAN_NAMESPACE -D_REENTRANT -DGUNIT_NO_GOOGLE3 -DKH_MAX_NUM_JOBS_COEFF=16 -fPIC -I/home/user/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/src/glu/sgi/libtess/../include -I/home/user/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/include -I/usr/include -INATIVE-REL-x86_64/include -INATIVE-REL-x86_64 -I. -INATIVE-REL-x86_64/common -Icommon -Icommon/khmisc -Ikeyhole NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/src/glu/sgi/libtess/priorityq.c
cc1: error: -Werror=unused-local-typedefs: No option -Wunused-local-typedefs
cc1: error: -Werror=unused-but-set-variable: No option -Wunused-but-set-variable
scons: *** [NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/src/glu/sgi/libtess/tessmono.o] Error 1
cc1: error: -Werror=unused-local-typedefs: No option -Wunused-local-typedefs
cc1: error: -Werror=unused-but-set-variable: No option -Wunused-but-set-variable
scons: *** [NATIVE-REL-x86_64/third_party/glu/Mesa-7.11/src/glu/sgi/libtess/priorityq.o] Error 1
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.
```
I am not sure if this is related to the libpng issue I was seeing before, or something else. Anyone seen this before?

**Comment by tst-ccamp** [comment] 2017-07-12 21:02
Ah, OK, now it's making a bit more sense. It seems that we require a newer version of g++. That might also be the reason the include check fails. I'd suggest updating the compiler to version 4.8 and try again.

**Comment by irteza123** [comment] 2017-07-13 06:45
i am having a problem when i run command scons -j8 release=1 build
it shows error
scons: Reading SConscript files ...
Unrecognized option: 'release'
What can i do guys

**Comment by sibucan** [comment] 2017-07-13 12:33
@tst-ccamp After upgrading gcc/g++ to version 4.8.4, I can confirm that the project builds successfully. I also uncommented the earlier scons check for libpng12 and the checks passed. It seems that gcc/g++ 4.4 is too old to be supported. Thanks for your help!

@irteza123 Are you sure you're running the command inside the `~/earthenterprise/earth_enterprise` directory?

**Comment by irteza123** [comment] 2017-07-13 17:15
Yes i am running this command in specified directory. I don't know what is
wrong with it

On 13 Jul 2017 17:33, "sibucan" <notifications@github.com> wrote:

@tst-ccamp <https://github.com/tst-ccamp> After upgrading gcc/g++ to
version 4.8.4, I can confirm that the project builds successfully. I also
uncommented the earlier scons check for libpng12 and the checks passed. It
seems that gcc/g++ 4.4 is too old to be supported. Thanks for your help!

@irteza123 <https://github.com/irteza123> Are you sure you're running the
command inside the ~/earthenterprise/earth_enterprise directory?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/earthenterprise/issues/319#issuecomment-315064115>,
or mute the thread

**Comment by tst-ccamp** [comment] 2017-07-13 17:50
@irteza123 My guess would be that you have an out of date version of the master branch checked out. We made a change a while back that enabled the build command from the earth_enterprise directory, but before that it didn't support the command. Can you make sure that you have the latest version in your local repo?

**Comment by tst-lsavoie** [comment] 2017-09-06 20:51
It's been a while since there was any action on this, so I'm going to close it.  @irteza123 if you're still having trouble feel free to reopen the ticket or post in the slack channel.

**Closed by tst-lsavoie** 2017-09-06 20:51 UTC
Labels: question
